let token='',snapshot=null,dirty=false;
const $=id=>document.getElementById(id);
const groups={products:'产品资料',scenes:'场景',angles:'机位角度',lights:'光线',compositions:'构图',flavors:'新增风味',cuts:'切面结构',packaging:'包装与承托',goldens:'黄金组合说明',common:'通用摄影要求'};
const labels={name:'名称',category:'分类',ingredients:'主要组成',appearance:'外观与口感',whole:'完整状态',cut:'切分方式',macro:'局部质地',finishing:'制作操作',avoid:'本款避免项',desc:'简介',text:'提示词正文',hint:'提示',structure:'内部结构',avoidCut:'切面避免项',preferredAngle:'推荐角度说明',spec:'包装结构',openState:'开合状态',container:'容器',consistency:'系列一致性',label:'组合标题',why:'推荐理由',quality:'摄影质量要求',negative:'通用避免项'};
function status(text){$('status').textContent=text;}
async function api(route,method='GET',body){
 const headers={Authorization:'Bearer '+token};
 if(method!=='GET'){headers['If-Match']=snapshot.revision;headers['Content-Type']=typeof body==='string'?'text/html; charset=utf-8':'application/json';}
 const response=await fetch('/api/admin/'+route,{method,headers,body:body===undefined?undefined:typeof body==='string'?body:JSON.stringify(body)});
 const result=await response.json();if(!response.ok)throw new Error(result.error||'操作失败');return result;
}
function options(select,items){select.replaceChildren(...items.map(([value,text])=>{const option=document.createElement('option');option.value=value;option.textContent=text;return option;}));}
function renderItems(preferred){const group=$('group').value;options($('item'),Object.entries(snapshot.defaults[group]).sort(([a],[b])=>a.localeCompare(b,undefined,{numeric:true})).map(([id,fields])=>[id,id+' · '+(snapshot.config[group]?.[id]?.name||fields.name||fields.label||id)]));if(preferred&&Object.hasOwn(snapshot.defaults[group],preferred))$('item').value=preferred;renderFields();}
function renderFields(){const group=$('group').value,id=$('item').value;const merged={...snapshot.defaults[group][id],...snapshot.config[group]?.[id]};$('group').dataset.previous=group;$('item').dataset.previous=id;$('fields').replaceChildren();for(const [key,value]of Object.entries(merged)){const label=document.createElement('label');label.htmlFor='field-'+key;label.textContent=labels[key]||key;const field=document.createElement('textarea');field.id='field-'+key;field.dataset.key=key;field.value=value;field.maxLength=20000;field.addEventListener('input',()=>dirty=true);$('fields').append(label,field);}dirty=false;}
async function load(){const group=$('group').value,item=$('item').value;snapshot=await api('state');$('login').hidden=true;$('workspace').hidden=false;$('token').value='';options($('group'),Object.entries(groups));if(group)$('group').value=group;renderItems(item);options($('history'),snapshot.history.map(x=>[x,x.replace(/\.json$/,'')]));$('rollback').disabled=!snapshot.history.length;$('revision').textContent='版本 '+snapshot.revision.slice(0,12);}
async function action(callback){const buttons=[...document.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await callback();}catch(error){status(error.message);}finally{buttons.forEach(b=>b.disabled=false);if(snapshot)$('rollback').disabled=!snapshot.history.length;}}
$('login').addEventListener('submit',event=>{event.preventDefault();token=$('token').value.trim();action(async()=>{await load();status('已载入。修改后点击发布。');});});
$('group').addEventListener('change',()=>{if(dirty&&!confirm('未发布的修改将丢失，继续切换？')){$('group').value=$('group').dataset.previous;return;}renderItems();$('group').dataset.previous=$('group').value;});
$('item').addEventListener('change',()=>{if(dirty&&!confirm('未发布的修改将丢失，继续切换？')){$('item').value=$('item').dataset.previous;return;}renderFields();$('item').dataset.previous=$('item').value;});
$('editor').addEventListener('submit',event=>{event.preventDefault();action(async()=>{const group=$('group').value,id=$('item').value,config=structuredClone(snapshot.config);config[group]??={};config[group][id]??={};for(const field of $('fields').querySelectorAll('textarea')){if(field.value===snapshot.defaults[group][id][field.dataset.key])delete config[group][id][field.dataset.key];else config[group][id][field.dataset.key]=field.value;}await api('config','PUT',config);await load();status('提示词已发布，上一版已备份。');});});
$('reset-item').addEventListener('click',()=>{if(!confirm('恢复本条原始预设并立即发布？'))return;action(async()=>{const config=structuredClone(snapshot.config);if(config[$('group').value])delete config[$('group').value][$('item').value];await api('config','PUT',config);await load();status('本条已恢复原始预设。');});});
$('reload').addEventListener('click',()=>{if(dirty&&!confirm('丢弃未发布的修改并重新载入？'))return;action(async()=>{await load();status('已重新载入。');});});
$('export').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot.config,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='halfday-prompt-overrides.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
$('publish-interface').addEventListener('click',()=>{const file=$('interface-file').files[0];if(!file)return status('请先选择新版 index.html');if(file.size>2*1024*1024)return status('文件超过 2 MB');if(!confirm('发布新版界面？系统会保留上一版供回退。'))return;action(async()=>{await api('interface','PUT',await file.text());await load();$('interface-file').value='';status('新版界面已发布。请打开公开工具核对效果，需要时可在下方回退。');});});
$('rollback').addEventListener('click',()=>{if(!confirm('将界面与提示词一起回退到所选版本？'))return;action(async()=>{await api('rollback','POST',{filename:$('history').value});await load();status('已回退；回退前的版本也已保留。');});});
$('logout').addEventListener('click',()=>{token='';snapshot=null;dirty=false;$('fields').replaceChildren();$('workspace').hidden=true;$('login').hidden=false;$('token').value='';status('已退出。');});
addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
